version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./go-backend
    container_name: notes_backend
    restart: always
    env_file:
      - ./go-backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/notesdb?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./react-ts-frontend
    container_name: notes_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
